image:
  name: hashicorp/terraform:light
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'


variables:
    AWS_KEY_ID : AWS_ACCESS_KEY_ID
    AWS_SECRET_KEY : AWS_SECRET_ACCESS_KEY
    AWS_ DEFAULT_REGION : "us-east-1"

before_script:
    - terraform --version
    - terraform init 

stages:
    - validate
    - plan
    - apply
    - destroy

validate:
    stage: validate
    script:
        - terraform validate

plan:
    stage: plan
    script:
        - terraform plan -out "planfile"
    dependencies:
        - validate
    artifacts:
        paths:
            - planfile

apply:
    stage: apply    
    dependencies:
        - plan
    script:
    - terraform apply -input=false "planfile"
    when: manual

destroy:
    stage: destroy
    script:
        - terraform destroy -auto-approve
    when: manual